# 1. Build Stage
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

# Use quotes for the filename with spaces
COPY "HOLLOW OCTAGONAL PYRAMID CALCULATOR.csproj" ./
RUN dotnet restore "HOLLOW OCTAGONAL PYRAMID CALCULATOR.csproj"

COPY . .
RUN dotnet build "HOLLOW OCTAGONAL PYRAMID CALCULATOR.csproj" -c Release -o /app/build

# 2. Publish Stage
FROM build AS publish
RUN dotnet publish "HOLLOW OCTAGONAL PYRAMID CALCULATOR.csproj" -c Release -o /app/publish /p:UseAppHost=false

# 3. Runtime Stage
FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --from=publish /app/publish .

# Render/Heroku dynamic port binding
ENV ASPNETCORE_URLS=http://+:${PORT:-8080}
EXPOSE 8080

# Use the exact DLL name generated by your project
ENTRYPOINT ["dotnet", "HOLLOW OCTAGONAL PYRAMID CALCULATOR.dll"]